language: generic 

services:
  - docker

before_install:
  - docker build -t emersonmoizes/docker-react -f Dockerfile.dev .

script:
  - docker run emersonmoizes/docker-react npm run test -- --coverage
